<font size = 6>Nashpy VS quantecon</font>

In [1]:
# install the tools you will use later
%pip install --upgrade setuptools
%pip install --upgrade pip
%pip install nashpy
%pip install quantecon

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
     |████████████████████████████████| 1.1 MB 162 kB/s            
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.5.3
    Uninstalling setuptools-58.5.3:
      Successfully uninstalled setuptools-58.5.3
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
DEPRECATION: Configuring installation scheme with distuti

<font face = Times size=4>

***Nashpy: Chiken Game***
    
</font>

---

<font face = Times size = 4>
    
***Example - Chiken Game:***

</font>

<div align="center">
<img src="https://miro.medium.com/max/1400/1*dpyN8Y5t2l36s_LeBOXnHg.jpeg" width="40%"/>
    </div>
<font face = Times size = 3>
    <center> Fig: Chiken Game </center>
    </font>




<font face = Times size = 4>
    
***Question:*** What is the equilibrium strategy profile?

</font>

<font face = Times size=4>

***Using Nashpy:***
    
</font>

In [16]:
import nashpy as nash
import numpy as np

# Creater the game with the payoff matrix

A = np.array([[0, -1],
              [1, -100]]) # A is the row player

B = np.array([[0, 1],
              [-1, -100]]) # B is the column player

In [17]:
# Form the game
CKgame = nash.Game(A,B)
CKgame

Bi matrix game with payoff matrices:

Row player:
[[   0   -1]
 [   1 -100]]

Column player:
[[   0    1]
 [  -1 -100]]

In [18]:
# Find the Nash Equilibrium with Support Enumeration
equilibria = CKgame.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.99, 0.01]), array([0.99, 0.01]))


Interpretation of the results:

In the output of Nashpy, each tuple represents a strategy set. The first two tuples represent the pure strategy NE, which are TOP LEFT and BOTTOM RIGHT. The third tuple shows the mixed strategy NE.

<font face = Times size = 4>

***Using QuantEcon:*** 
    
</font>

<font face = Times size = 4>

***Form the game:*** In the following part, three ways to form a game will be shown.
    
</font>

In [19]:
# import the QuantEcon package
import quantecon.game_theory as gt
import numpy as np

# The first way to form the game: by the payoff matrix
chiken_game_matrix = np.array([[(0, 0), (-1, 1)],
                                    [(1, -1), (-100, -100)]])

g_CG = gt.NormalFormGame(chiken_game_matrix)
print(g_CG)

2-player NormalFormGame with payoff profile array:
[[[   0,    0],  [  -1,    1]],
 [[   1,   -1],  [-100, -100]]]


In [21]:
# The second way to form the game: by players
player0 = gt.Player([[0, -1],
              [1, -100]])

# Please pay attention to the difference here!!!
player1 = gt.Player([[0, -1],
              [1, -100]])

# Pass in the two players
g_CG = gt.NormalFormGame((player0, player1))
print(g_CG)

2-player NormalFormGame with payoff profile array:
[[[   0,    0],  [  -1,    1]],
 [[   1,   -1],  [-100, -100]]]


In [22]:
# the third way to form the game: by actions (Not recommanded)

# 2 players, each of whom has 2 actions
g_CG = gt.NormalFormGame((2, 2))
g_CG[0, 0] = 0, 0
g_CG[0, 1] = -1, 1
g_CG[1, 0] = 1, -1
g_CG[1, 1] = -100, -100

print(g_CG)

2-player NormalFormGame with payoff profile array:
[[[   0.,    0.],  [  -1.,    1.]],
 [[   1.,   -1.],  [-100., -100.]]]


Short Summay:

There are three ways to form a game using QuantEcon. Personally I will recommand you to use the first way (directly pass in the payoff matrix). This is the most intuitive way. Also, if you used to use Nashpy, the logic of forming a game by Nashpy and by QuantEcon are different, please pay attention to that.



<font face = Times size = 4>

***Find the Nash equilibrium:*** 
    
    
</font>

In [23]:
# Finding the Nash equilibrium: pure_nash_brute

NE = gt.pure_nash_brute(g_CG)
print(NE)

[(0, 1), (1, 0)]


In [24]:
# Finding the Nash equilibrium: support_enumeration

NE = gt.support_enumeration(g_CG)
print(NE)

[(array([1., 0.]), array([0., 1.])), (array([0., 1.]), array([1., 0.])), (array([0.99, 0.01]), array([0.99, 0.01]))]


In [25]:
NE = gt.vertex_enumeration(g_CG)
print(NE)

[(array([1., 0.]), array([0., 1.])), (array([0., 1.]), array([1., 0.])), (array([0.99, 0.01]), array([0.99, 0.01]))]


Short Summay:

We introduced three way to solve for the Nash equilibrium. Pure_nash_brute is able to return the pure strategy NE. Support_enumeration and vertex_enumeration both computes mixed-action Nash equilibria of a 2-player normal form game by enumeration and matching of vertices of the best response polytopes, but the latter seems to run faster than the former.

